/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda.film;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author julio.ospina
 */
public class formAgregarFilm extends javax.swing.JDialog {

    /**
     * Creates new form formAgregarFilm
     */
    
    public formAgregarFilm(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTituloFilm = new javax.swing.JTextField();
        textDescripcionFilm = new javax.swing.JTextField();
        textañoFilm = new javax.swing.JTextField();
        textDuracionRentFilm = new javax.swing.JTextField();
        textDuracionFilm = new javax.swing.JTextField();
        cmbLenguajeFilm = new javax.swing.JComboBox<>();
        textCostoRemplazoFilm = new javax.swing.JTextField();
        btnGuardarFilm = new javax.swing.JButton();
        btnCancelarCreacionFilm = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        trueTrailers = new javax.swing.JRadioButton();
        trueCommentaries = new javax.swing.JRadioButton();
        trueDeleteEscenes = new javax.swing.JRadioButton();
        trueBehindEscenes = new javax.swing.JRadioButton();
        textRateRenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        textTituloFilm.setText("[Titulo]");
        textTituloFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloFilmActionPerformed(evt);
            }
        });

        textDescripcionFilm.setText("[Descripcion]");
        textDescripcionFilm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textDescripcionFilmFocusGained(evt);
            }
        });
        textDescripcionFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDescripcionFilmActionPerformed(evt);
            }
        });

        textañoFilm.setText("año Produccion");

        textDuracionRentFilm.setText("duracion  renta film");

        textDuracionFilm.setText("minutos duracion");

        cmbLenguajeFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textCostoRemplazoFilm.setText("costo Remplazo");

        btnGuardarFilm.setText("Guardar");
        btnGuardarFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFilmActionPerformed(evt);
            }
        });

        btnCancelarCreacionFilm.setText("Cancelar");
        btnCancelarCreacionFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCreacionFilmActionPerformed(evt);
            }
        });

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("CONTENIDO ADICIONAL");

        trueTrailers.setText("Trailers");

        trueCommentaries.setText("Comentarios");

        trueDeleteEscenes.setText("Escenas Borradas");

        trueBehindEscenes.setText("Escenas Detras de camara");

        textRateRenta.setText("[Rate Renta]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textRateRenta, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbCategoria, 0, 141, Short.MAX_VALUE)
                        .addComponent(textDuracionFilm)
                        .addComponent(textDuracionRentFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(textañoFilm)
                        .addComponent(textDescripcionFilm)
                        .addComponent(textTituloFilm)
                        .addComponent(cmbLenguajeFilm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textCostoRemplazoFilm)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trueTrailers)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trueCommentaries)
                            .addComponent(trueDeleteEscenes)
                            .addComponent(trueBehindEscenes))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardarFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarCreacionFilm)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTituloFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDescripcionFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trueTrailers)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trueCommentaries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textañoFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trueDeleteEscenes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLenguajeFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trueBehindEscenes))
                .addGap(18, 18, 18)
                .addComponent(textDuracionRentFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textDuracionFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textCostoRemplazoFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarFilm)
                    .addComponent(btnCancelarCreacionFilm)
                    .addComponent(textRateRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTituloFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloFilmActionPerformed

    private void textDescripcionFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDescripcionFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDescripcionFilmActionPerformed

    private void textDescripcionFilmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDescripcionFilmFocusGained
        // TODO add your handling code here:
        textDescripcionFilm.setText("");
    }//GEN-LAST:event_textDescripcionFilmFocusGained

    private void llenarCombobox()
    {
        
        conexionBD myConector = new conexionBD();
        ResultSet resultset = null;
        try

        {
            
            resultset = myConector.statement.executeQuery("SELECT * FROM language");
            
            while (resultset.next()) {
                cmbLenguajeFilm.addItem(resultset.getString("language.name"));
            }
            
            

        }
        catch( SQLException sqlException)
        {
            sqlException.printStackTrace();
        }
        try

        {
            
            resultset = myConector.statement.executeQuery("SELECT * FROM category");
            
            while (resultset.next()) {
                cmbCategoria.addItem(resultset.getString("category.name"));
            }
            
            

        }
        catch( SQLException sqlException)
        {
            sqlException.printStackTrace();
        }
        
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        cmbLenguajeFilm.removeAllItems();
        cmbCategoria.removeAllItems();
        llenarCombobox();
        
        
    
        
        
    }//GEN-LAST:event_formWindowActivated

    private void btnCancelarCreacionFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCreacionFilmActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarCreacionFilmActionPerformed

    private void btnGuardarFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFilmActionPerformed
    /*    // TODO add your handling code here:
    private javax.swing.JButton btnCancelarCreacionFilm;
    private javax.swing.JButton btnGuardarFilm;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbLenguajeFilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textCostoRemplazoFilm;
    private javax.swing.JTextField textDescripcionFilm;
    private javax.swing.JTextField textDuracionFilm;
    private javax.swing.JTextField textDuracionRentFilm;
    private javax.swing.JTextField textTituloFilm;
    private javax.swing.JTextField textañoFilm;
    private javax.swing.JRadioButton trueBehindEscenes;
    private javax.swing.JRadioButton trueCommentaries;
    private javax.swing.JRadioButton trueDeleteEscenes;
    private javax.swing.JRadioButton trueTrailers;
    // End of variables declaration */
        if( !textTituloFilm.getText().trim().isEmpty() && !textCostoRemplazoFilm.getText().trim().isEmpty() && !textDuracionRentFilm.getText().trim().isEmpty() && !textRateRenta.getText().trim().isEmpty() )
        {
            //datos obligatorios correctos.
            
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Faltan datos obligatorios");
            
            
        }
        
    }//GEN-LAST:event_btnGuardarFilmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAgregarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAgregarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAgregarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAgregarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formAgregarFilm dialog = new formAgregarFilm(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCreacionFilm;
    private javax.swing.JButton btnGuardarFilm;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbLenguajeFilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textCostoRemplazoFilm;
    private javax.swing.JTextField textDescripcionFilm;
    private javax.swing.JTextField textDuracionFilm;
    private javax.swing.JTextField textDuracionRentFilm;
    private javax.swing.JTextField textRateRenta;
    private javax.swing.JTextField textTituloFilm;
    private javax.swing.JTextField textañoFilm;
    private javax.swing.JRadioButton trueBehindEscenes;
    private javax.swing.JRadioButton trueCommentaries;
    private javax.swing.JRadioButton trueDeleteEscenes;
    private javax.swing.JRadioButton trueTrailers;
    // End of variables declaration//GEN-END:variables
}
